import { DatabaseColumnSchema } from "./DatabaseColumnSchema";

/**
 * This is a collection schema.
 * It describes what's necessary to deploy a data schema.
 * Important to notice that you don't have to describe the columns.
 *
 * @author Rodrigo Portela
 */
export interface DatabaseCollectionSchema {
  name: string;
  primaryKey: string | string[];
  columns?: DatabaseColumnSchema[];
  autoGenerated?: boolean;
}
